web/config/routes.rb
Web::Application.routes.draw do
  resources :submissions

  match '/submissions/with_file', :to => 'submissions#create_with_file'

  resources :problems do
    resources :testcases
    resources :submissions
  end

  get "home/index"

  match '/auth/:provider/callback', :to => 'sessions#callback'
  match '/logout' => 'sessions#destroy', :as => :logout

  root :to => 'home#index'

end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def login_required
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      redirect_to root_path
    end

  end

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

web/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

web/app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(params[:problem])

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render json: @problem, status: :created, location: @problem }
      else
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :no_content }
    end
  end
end

web/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

web/app/controllers/submissions_controller.rb
# -*- coding: utf-8 -*-
class SubmissionsController < ApplicationController

  require 'net/http'

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all.reverse
    @watch = params[:watch].to_i
    if @watch == 0 then 
      @watch = nil
    end
    if @watch then
      my_submission = (@submissions.select do |x| x.id == @watch end)[0]
      @watch = nil if my_submission && (not self.class.helpers.now_judging?(my_submission))
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submissions }
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @submission = Submission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/new
  # GET /submissions/new.json
  def new
    @submission = Submission.new
    @submission.problem = params[:problem].to_i if params[:problem]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submission }
    end
  end

  def create_base params
    @submission = Submission.new(params)
    flg = @submission.save

    Thread.new do # TODO こんなんでいいのだろうか？ non-blocking
      Net::HTTP.get("localhost", "/submissions/judge/#{@submission.id}", port = 4000 )
    end       

    redirect_to :action => 'index', :watch => @submission.id
  end

  # POST /submissions
  # POST /submissions.json
  def create
    params[:submission][:verdict] = 'pending'
    create_base(params[:submission])    
  end

  def create_with_file
    tmp = {}
    tmp[:author] = params[:author]
    tmp[:problem] = params[:problem]
    tmp[:lang] = params[:lang]
    tmp[:code] = params[:file]['htmldata'].read
    tmp[:verdict] = 'pending'
    create_base(tmp)
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :no_content }
    end
  end
end

web/app/controllers/testcases_controller.rb
class TestcasesController < ApplicationController

  def new 
    problem_id = params[:problem_id]
    @problem = Problem.find(problem_id)

    respond_to do |format|
      format.html
      format.json { render json: @testcase }
    end
  end

  def index
    @problem_id = params[:problem_id]
    @testcases = Problem.find(@problem_id).testcases

    respond_to do |format|
      format.html
      format.json { render json: @testcases }
    end
  end

  def create
    @problem = Problem.find(params[:problem_id])
    @testcase = @problem.testcases.create(params[:testcase])
    redirect_to problem_path(@problem)
  end

  def destroy
    @testcase = Testcase.find(params[:id])
    @testcase.destroy

    respond_to do |format|
      format.html { redirect_to :action => 'index' }
      format.json { head :no_content }
    end
  end

end

web/app/helpers/submissions_helper.rb
module SubmissionsHelper

  def normalize_whitespaces str
    str.strip.gsub(/[\r\n\t ]+/, ' ')
  end

  def judge (lang, code, testcases)
    
    case lang
    when 'c++', 'C++'
      
      compile = "cat <<END | g++ -x c++ -std=c++0x -O2 -o /tmp/a.out -
#{code}
END"
      
      return 'compile error' unless system(compile)
      
      ok = testcases.all? do |testcase|
        answer = testcase.output
        output = `cat <<END | /tmp/a.out
#{testcase.input}
END`
        File.write("/home/kfujima/log.txt", output)
        (normalize_whitespaces answer) == (normalize_whitespaces output)
      end
      
      return ok ? 'AC' : "WA" 
    else
      return 'unknown lang'
    end
  end

end

web/app/views/home/index.html.erb
<h1>Welcome!</h1>
<p>今のところの機能</p>
<p>
  <ul>
    <li>問題の追加</li>
    <li>テストケースの追加</li>
    <li>回答提出</li>
  </ul>
</p>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>no title</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">no title</a>
          <ul class="nav pull-left">
            <li><%= link_to 'Home', :root %></a></li>
            <li><%= link_to 'Problems', problems_path %></a></li>
            <li><%= link_to 'Submissions', submissions_path %></a></li>
          </ul>
          <ul class="nav pull-right">
            <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= image_tag(twitter_icon(current_user.name), :border => '0', :width => '20px') %>
                <%= current_user.name %>
                
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'LOGOUT', logout_path %></li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to image_tag('/images/signin.png'), '/auth/twitter' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span10 offset1">
            <%= yield %>
          </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <center><p>&copy; wistery_k open source at <a href="https://github.com/wistery-k/oj">github</a></p></center>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

web/app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :statement %><br />
    <%= f.text_area :statement %>
  </div>
  <div class="field">
    <%= f.label :time_limit %><br />
    <%= f.text_field :time_limit %>
  </div>
  <div class="field">
    <%= f.label :memory_limit %><br />
    <%= f.text_field :memory_limit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/problems/_submit_form.html.erb
<%= form_tag "/submissions/with_file", :multipart=>true do %>
  <% if not current_user then %>
  <div class="field">
    <%= label_tag :author %><br />
    <%= text_field_tag :author %>
  </div>
  <% else %>
    <div class="field">
    <%= hidden_field_tag 'author', current_user.name %>
  </div>
  <% end %>
  <div class="field">
    <%= hidden_field_tag 'problem', @problem.id %>
  </div>
  <div class="field">
    <%= select_tag :lang, options_for_select(%w(c++ java ruby python ocaml)) %>
  </div>
  <div class="field">
    <%= file_field :file, :htmldata %>
  </div>
  <div class="actions">
    <%= submit_tag "submit" %>
  </div>
<% end %>

web/app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

web/app/views/problems/index.html.erb
<h1 style="margin-bottom:10px;">problems</h1>

<table class="table table-striped">
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Statement</th>
    <th>Time limit</th>
    <th>Memory limit</th>
  </tr>

<% @problems.each do |problem| %>
  <tr>
    <td><%= problem.id %></td>
    <td><%= link_to problem.title, problem %></td>
    <td><%= problem.statement[0..20] %>...</td>
    <td><%= problem.time_limit %></td>
    <td><%= problem.memory_limit %></td>
  </tr>
<% end %>
</table>

web/app/views/problems/new.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

web/app/views/problems/show.html.erb
<div class="container">
  <div class="content">
    <div class="row">
      <div class="span7">
        <center>
          <p>
            <h1><%= @problem.title %></h2>
          </p>
          
          <p>
            <b>Time limit:</b>
            <%= @problem.time_limit %> s
          </p>
          
          <p>
            <b>Memory limit:</b>
            <%= @problem.memory_limit %> MiB
          </p>
          </center>
        <p>
          <%=raw hbr @problem.statement %>
        </p>
        
        <h3>Sample</h3>
        <% @problem.testcases[0..2].each_with_index do |testcase,index| %>
        <p>
          <b>Input<%= index %>:</b><br />
          <pre><%= testcase.input %></pre>
        </p>
        
        <p>
          <b>Output<%= index %>:</b><br />
          <pre><%= testcase.output %></pre>
        </p>
        <% end %>
      </div>
        
      <div class="span3">
        <div class="col">
          <div class="well sidebar-nav">
            <h3>submit</h3>
            <%= link_to "submit form", :controller => 'submissions', :action => 'new', :problem => @problem.id %>
          </div>
          <div class="well sidebar-nav">
            <h3>quick submit</h3>
            <%= render 'submit_form' %>
          </div>
          <div class="well sidebar-nav">
            <h3>choices</h3>
            <ul class="nav nav-list">
              <li class="nav-header">anyone</li>
              <li><%= link_to "see testcases", "/problems/#{@problem.id}/testcases" %></li>
              <li class="nav-header">writer</li>
              <li><%= link_to "add testcase", "/problems/#{@problem.id}/testcases/new"  %></li>
              <li><%= link_to "view stats", "#"  %></li>
              <li><%= link_to "edit problem", edit_problem_path(@problem)  %></li>
              <li><%= link_to 'delete problem', @problem, confirm: 'Are you sure?', method: :delete %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

web/app/views/submissions/_form.html.erb
<% if current_user then @submission.author = current_user.name end %>
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.number_field :problem %>
  </div>
  <div class="field">
    <%= f.select :lang, %w(c++ java ruby python ocaml) %>
  </div>
  <div class="field">
    <%= f.text_area :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

web/app/views/submissions/index.html.erb
<h1 style="margin-bottom:10px;">submissions</h1>

<table class="table table-striped">
  <tr>
    <th>#</th>
    <th>Author</th>
    <th>Problem</th>
    <th>Lang</th>
    <th>Verdict</th>
    <th></th>
    <th></th>
  </tr>

<% @submissions.each do |submission| %>
  <tr>
    <td><%= submission.id %></td>
    <td><%= submission.author %></td>
    <td><%= problem_link submission.problem %></div></td>
    <td><%= submission.lang %></td>
    <td>
      <%=raw colorize_verdict submission.verdict %>
      <% if submission.id == @watch %>
        <img src="/images/loading.gif" width="30px"/>
      <% end %>
    </td>
    <td><%= link_to 'Detail', submission, :class => 'btn' %></td>
    <td><%= link_to image_tag('/images/delete_red.png', :border => '0', :width => '20px'), submission, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<script>

  function check(watch){
    callback = function(json){
      if(json["verdict"] != "pending"){
        window.location.reload();
      }
    };
    x = $.getJSON("/submissions/"+watch+".json", {}, callback);
  }

  <% if @watch %>
  (function(){
    watch = <%= "#{@watch}" %>;
    setInterval("check(watch)", 1000);
  })();
  <% end %>
</script>

web/app/views/submissions/new.html.erb
<h1>Submit</h1>

<hr>

<%= render 'form' %>

web/app/views/submissions/show.html.erb
<p>
  <b>Author:</b>
  <%= @submission.author %>
</p>

<p>
  <b>Problem:</b>
  <%= @submission.problem %>
</p>

<p>
  <b>Lang:</b>
  <%= @submission.lang %>
</p>

<p>
  <b>Verdict:</b>
  <%=raw colorize_verdict @submission.verdict %>
</p>

<p>
  <b>Code:</b><br />
  <pre><%= @submission.code %></pre>
</p>

<hr/>

<p>
  <b>Tests:</b><br />
  <% testcases = Problem.find(@submission.problem).testcases %>
  <% @submission.testresults.each_with_index do |testresult, i| %>
  <p><b>test #<%= i %></b></p>
  <p>verdict: <%=raw colorize_verdict testresult.verdict %></p>
  <p>output</p>
  <pre><%= testresult.output %></pre>
  <p>answer</p>
  <pre><%= testcases[i].output %></pre>
  <% end %>
</p>

web/app/views/testcases/index.html.erb
<h1 style="margin-bottom:10px;">Problem #<%= @problem_id %> All Testcases</h1>
<% @testcases.each_with_index do |testcase,index| %>
<h3>testcase #<%= index %> <%= link_to image_tag('/images/delete_red.png', :border => '0', :width => '20px'), "/problems/#{@problem_id}/testcases/#{testcase.id}", confirm: 'Are you sure?', method: :delete %></h3>
<p>
  <b>Input:</b><br />
  <pre><%= testcase.input %></pre>
</p>

<p>
  <b>Output:</b><br />
  <pre><%= testcase.output %></pre>
</p>
<% end %>

<% if false %>
<p>
  <h2>Add testcase:</h2>
  <%= form_for([@problem, @problem.testcases.build]) do |f| %>
  <div class="field">
    <%= f.label :input %><br />
    <%= f.text_area :input %>
  </div>
  <div class="field">
    <%= f.label :output %><br />
    <%= f.text_area :output %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</p>
<% end %>

web/app/views/testcases/new.html.erb
<p>
  <h2>New testcase:</h2>
  <%= form_for([@problem, @problem.testcases.build]) do |f| %>
  <div class="field">
    <%= f.label :input %><br />
    <%= f.text_area :input %>
  </div>
  <div class="field">
    <%= f.label :output %><br />
    <%= f.text_area :output %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</p>